spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trip
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      format_sql: true


logging:
  level:
    com.gabojago.trip : DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    context-path: /api
  port:
    8080

