server:
  servlet:
    context-path: /api
  port:
    8080

spring :
  profiles:
    default: prod
  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
