name: Backend Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - develop

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: 권한부여 # (0)
        run: chmod +x gradlew
        
      - name: springboot application build # (1)
        run: ./gradlew clean compileJava bootJar
        
      - name: docker image build # (2)
        run: docker compose build

      - name: Docker Hub login # (3)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker image check # (4)
        run: docker images
        
      - name: Docker Hub 퍼블리시 # (4)
        run: docker push ynwoo/onepick_test

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          port: 22

          script: |
            # 실행중인 컨테이너 삭제
            docker rm -f onepick_backend
            
            # 이미지 삭제
            docker rmi -f ynwoo/onepick_test
            
            docker pull ynwoo/onepick_test
            
            # docker run -d -p 8080:8080 --name <container_name> <docker_hub_username>/<image_name>
            docker run -d --name onepick_backend --env-file ./config/.env -p 8080:8080 ynwoo/onepick_test



            # code를 pull 받아서 하는 방법
            # cd ~/Gabojago_Backend/
            # git pull
            # chmod +x gradlew
            # ./gradlew clean compileJava bootJar
            # 자바 빌드 -> .jar
            # ./gradle build
            # 폴더 이동 및 빌드 된 jar 파일 실행
            # java -jar build/libs/trip-0.0.1-SNAPSHOT.jar
            # dockerhub를 이용한 방법
